apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  labels:
    app: postgres-cm
data:
  POSTGRES_DB: dbname
  POSTGRES_USER: username
  POSTGRES_PASSWORD: pgpassword

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: linode-block-storage # linode-block-storage-retain

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres-statefulset
spec:
  replicas: 1
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgres-statefulset
  template:
    metadata:
      labels:
        app: postgres-statefulset
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres-port
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-cm
          volumeMounts:
            - name: postgres-db-vol
              mountPath: /var/lib/postgresql/data
      initContainers:
        - name: delete-existing-data
          image: alpine:latest
          command: ["sh", "-c", "rm -rf /mnt/*"]
          volumeMounts:
            - name: postgres-db-vol
              mountPath: /mnt
      volumes:
         - name: postgres-db-vol
           persistentVolumeClaim: 
              claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  type: ClusterIP # 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres-port
  selector:
    app: postgres-statefulset

# postgres://username@pgpassword:postgres-lb-service.default.svc.cluster.local/dbname
# kubectl port-forward svc/postgres-service 5430:5432
# PGPASSWORD=pgpassword psql -h localhost -p 5430 -U username -d dbname
